language: haskell

ghc:
  - 7.6
  - 7.8
  - 8.0

install:
  - cabal install --only-dependencies --enable-tests -fall_extensions
  - wget https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh

script:
  - sh ./travis.sh src
  - cabal configure --enable-tests -fall_extensions && cabal build && cabal test